version: '3.5'

services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
  db:
    build: ./dockersql/
    ports:
      - "3307:3306"
  frontend:
    build:
      context: ../frontend
    ports:
      - "8000:8000"